export const countriesIBANInfo = [
    { name_fa: 'آلبانی', name_code: 'AL', len: 28 },
    { name_fa: 'الجزیره', name_code: 'DZ', len: 24 },
    { name_fa: 'آندورا', name_code: 'AD', len: 24 },
    { name_fa: 'آنگولا', name_code: 'AO', len: 25 },
    { name_fa: 'اتریش', name_code: 'AT', len: 20 },
    { name_fa: 'آذربایجان', name_code: 'AZ', len: 28 },
    { name_fa: 'بحرین', name_code: 'BH', len: 22 },
    { name_fa: 'بوسنی و هرزه گوین', name_code: 'BA', len: 20 },
    { name_fa: 'بلژیک', name_code: 'BE', len: 16 },
    { name_fa: 'بنین', name_code: 'BJ', len: 28 },
    { name_fa: 'برزیل', name_code: 'BR', len: 29 },
    { name_fa: 'بلغارستان', name_code: 'BG', len: 22 },
    { name_fa: 'بورکینافاسو', name_code: 'BF', len: 27 },
    { name_fa: 'بوروندی', name_code: 'BI', len: 16 },
    { name_fa: 'کامرون', name_code: 'CM', len: 27 },
    { name_fa: 'کیپ ورد', name_code: 'CV', len: 25 },
    { name_fa: 'کاستاریکا', name_code: 'CR', len: 21 },
    { name_fa: 'کرواسی', name_code: 'HR', len: 21 },
    { name_fa: 'مصر', name_code: 'CY', len: 28 },
    { name_fa: 'جمهوری چک', name_code: 'CZ', len: 24 },
    { name_fa: 'دانمارک', name_code: 'DK', len: 18 },
    { name_fa: 'جمهوری دومینیکن', name_code: 'DO', len: 28 },
    { name_fa: 'استونی', name_code: 'EE', len: 20 },
    { name_fa: 'جزایر فارو', name_code: 'FO', len: 18 },
    { name_fa: 'فنلاند', name_code: 'FI', len: 18 },
    { name_fa: 'فرانسه', name_code: 'FR', len: 27 },
    { name_fa: 'گواتمالا', name_code: 'GT', len: 28 },
    { name_fa: 'گرجستان', name_code: 'GE', len: 22 },
    { name_fa: 'آلمان', name_code: 'DE', len: 22 },
    { name_fa: 'جبل الطارق', name_code: 'GI', len: 23 },
    { name_fa: 'یونان', name_code: 'GR', len: 27 },
    { name_fa: 'گرینلند', name_code: 'GL', len: 18 },
    { name_fa: 'مجارستان', name_code: 'HU', len: 28 },
    { name_fa: 'ایسلند', name_code: 'IS', len: 26 },
    { name_fa: 'ایران', name_code: 'IR', len: 26 },
    { name_fa: 'ایرلند', name_code: 'IE', len: 22 },
    { name_fa: 'اسراییل', name_code: 'IL', len: 23 },
    { name_fa: 'ایتالیا', name_code: 'IT', len: 27 },
    { name_fa: 'ساحل عاج', name_code: 'CI', len: 28 },
    { name_fa: 'اردن', name_code: 'JO', len: 30 },
    { name_fa: 'قزاقستان', name_code: 'KZ', len: 20 },
    { name_fa: 'کویت', name_code: 'KW', len: 30 },
    { name_fa: 'لتونی', name_code: 'LV', len: 21 },
    { name_fa: 'لبنان', name_code: 'LB', len: 28 },
    { name_fa: 'لیختن اشتاین', name_code: 'LI', len: 21 },
    { name_fa: 'لیتوانی', name_code: 'LT', len: 20 },
    { name_fa: 'لوکزامبورگ', name_code: 'LU', len: 20 },
    { name_fa: 'مقدونیه', name_code: 'MK', len: 19 },
    { name_fa: 'ماداگاسکار', name_code: 'MG', len: 27 },
    { name_fa: 'مالت', name_code: 'MT', len: 31 },
    { name_fa: 'موریتانی', name_code: 'MR', len: 27 },
    { name_fa: 'موریس', name_code: 'MU', len: 30 },
    { name_fa: 'مالی', name_code: 'ML', len: 28 },
    { name_fa: 'مولداوی', name_code: 'MD', len: 24 },
    { name_fa: 'موناکو', name_code: 'MC', len: 27 },
    { name_fa: 'مونتنگرو', name_code: 'ME', len: 22 },
    { name_fa: 'موزامبیک', name_code: 'MZ', len: 25 },
    { name_fa: 'هلند', name_code: 'NL', len: 18 },
    { name_fa: 'نروژ', name_code: 'NO', len: 15 },
    { name_fa: 'پاکستان', name_code: 'PK', len: 24 },
    { name_fa: 'فلسطین', name_code: 'PS', len: 29 },
    { name_fa: 'لهستان', name_code: 'PL', len: 28 },
    { name_fa: 'پرتقال', name_code: 'PT', len: 25 },
    { name_fa: 'قطر', name_code: 'QA', len: 29 },
    { name_fa: 'رومانی', name_code: 'RO', len: 24 },
    { name_fa: 'سن مارینو', name_code: 'SM', len: 27 },
    { name_fa: 'عربستان', name_code: 'SA', len: 24 },
    { name_fa: 'سنگال', name_code: 'SN', len: 28 },
    { name_fa: 'سن مارینو', name_code: 'RS', len: 22 },
    { name_fa: 'اسلواکی', name_code: 'SK', len: 24 },
    { name_fa: 'اسلونی', name_code: 'SI', len: 19 },
    { name_fa: 'اسپانیا', name_code: 'ES', len: 24 },
    { name_fa: 'سوئد', name_code: 'SE', len: 24 },
    { name_fa: 'سوئیس', name_code: 'CH', len: 21 },
    { name_fa: 'تونس', name_code: 'TN', len: 24 },
    { name_fa: 'ترکیه', name_code: 'TR', len: 26 },
    { name_fa: 'امارت متحده عربی', name_code: 'AE', len: 23 },
    { name_fa: 'انگلستان', name_code: 'GB', len: 22 },
    { name_fa: 'جزایر ویرجینیا', name_code: 'VG', len: 24 },
]
